### ISSUE TITLE
How to use the app

### ISSUE THREAD

**Issue by bitmap4** [yukino-org/yukimi#1]
cant figure out how to read manga/watch anime

**Comment by zyrouge** [comment]
It's a command-line application. There are no tutorials yet on how to use this but if you have basic knowledge of command-line applications, you should not struggle using this.

**Comment by bitmap4** [comment]
well i figured out almost everything the help command shows but i cant figure out how to stream a video or do anything with the manga apart from looking at their information
is it possible?

**Comment by zyrouge** [comment]
> well i figured out almost everything the help command shows but i cant figure out how to stream a video or do anything with the manga apart from looking at their information is it possible?

Use the `--mpv` to stream using mpv, and manga as if now can only be downloaded and viewed externally since there is now way to open multiple images at once.

**Comment by bitmap4** [comment]
> manga as if now can only be downloaded and viewed externally

I dont know how to download either, pls guide me

**Comment by zyrouge** [comment]
> > manga as if now can only be downloaded and viewed externally
> 
> I dont know how to download either, pls guide me

Pass in `--chapters 1-5` or `--episodes 1-5` (can be a only a single episode too) with `--download` flag.

**Comment by bitmap4** [comment]
I dont understand, where exactly can I pass those options
![Screenshot 2022-04-26 at 8 53 30 AM](https://user-images.githubusercontent.com/64366765/165213960-ec5b83eb-33db-4e1c-9f1c-c891887ae65d.png)

**Comment by bitmap4** [comment]
![Screenshot 2022-04-26 at 11 05 18 PM](https://user-images.githubusercontent.com/64366765/165359300-76311f3b-6679-4b50-9677-163c3152fb18.png)
Ohh I figured it out after taking a look at the source code, thanks
