### ISSUE TITLE
Suggestion: Using download destinations as variables

### ISSUE THREAD

**Issue by bitmap4** [yukino-org/yukimi#2]
I would love to be able to do something like this: 
`manga info fanfox.net https://fanfox.net/manga/solo_leveling/ -d -c 1-100 -o $manga/Solo\ Levelling`
Helps me keep organised and a certain manga reader requires the chapter folders to be in a single folder for a certain manga.

**Comment by zyrouge** [comment]
I think it is doable. But can you say how the variables will be defined?

**Comment by bitmap4** [comment]
I was thinking of using the same paths as the ones set with `--mangaDestination` and `--animeDestination` in settings

**Comment by zyrouge** [comment]
> I was thinking of using the same paths as the ones set with `--mangaDestination` and `--animeDestination` in settings

Ah I get it now.

**Comment by zyrouge** [comment]
:tada: Released in v1.0.8!
