### ISSUE TITLE
[Feature Request] parallel download 

### ISSUE THREAD

**Issue by edgehub-cloud** [yukino-org/yukimi#4]
Download whole season, with accepted rate limits  ( 3 episodes at a time)

**Comment by zyrouge** [comment]
Soon:tm:

**Comment by zyrouge** [comment]
🎉 Implemented as of v1.2.0! Let me know if you face some issues with it.

**Comment by edgehub-cloud** [comment]
> 🎉 Implemented as of v1.2.0! Let me know if you face some issues with it.

Alright
