### ISSUE TITLE
[error] Command Exception: Missing option: module

### ISSUE THREAD

**Issue by SirObby** [yukino-org/yukimi#5]
Getting error `[error] Command Exception: Missing option: module` when running seemingly correct syntax command?

The syntax is `yukimi anime search "anime name"` like the help command suggests?

**Comment by zyrouge** [comment]
Link to docs: https://yukino-org.github.io/wiki/yukimi/basic_usage/#searching-an-anime.
Also, I'm not sure if the cli works after the rewrite of the module. No other way to find out than trying I guess.
